a = input('Digite algo: ')
print('Dados do que foi digitado:')
print('Só tem espaços?', a.isspace())
print('É numérico?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É alfanumérico?', a.isalnum())
print('Está apenas em letras maiúsculas?', a.isupper())
print('Está apenas em letras minúsculas?', a.islower())
print('Está capitalizada?', a.istitle())
print('Todos os caracteres pertencem ao ASCII?', a.isascii())
print('Possui apenas dígitos decimais?', a.isdecimal())
print('Possui apenas dígitos?', a.isdigit())
print('É um identificador válido em Python?', a.isidentifier())
print('Todos seus caracteres são imprimíveis?', a.isprintable())
